### ISSUE TITLE
no translation file found for en

### ISSUE THREAD

**Issue by ultrasound1372** [kianoosh-shakeri/extream-download-manager#1]
I have downloaded this project, and since it uses a newer version of wxpython than I have normally installed I used pipenv to isolate it. I then brought up the shell and tried to run xdm.py, and go the following.
Traceback (most recent call last):
  File "xdm.py", line 21, in <module>
    lang=gettext.translation(langstring, localedir='locale', languages=[langstring])
  File "c:\python3\Lib\gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'en'
Attempting to run what you've compiled in the bin folder also terminates with fatal error, though because it's not console I can't tell what the error is. I see a .po file, don't you have to compile it into a .mo as well? What steps do I need to take to do that so it can maybe find it?

**Comment by kianoosh-shakeri** [comment]
Hello,
You can get poedit
[here](https://poedit.net/download)
Steps to compile the .po file to a .mo file is really straight. Open the .po file with poedit, press alt, then press c to find compile to .MO file, and use that option. A save as window shows up. Save the .MO file next to the .PO file without changing the name.
I just checked and the .MO files are already there. The .gitignore file was blocking the .MO format from being uploaded which I fixed a while ago. Try re-cloning the app
